name: django

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::208060188195:role/apiserverrole
          role-session-name: sampleSessionName
          aws-region: ap-northeast-2